### ISSUE TITLE
Update google maps token

### ISSUE THREAD

**Issue by jonduarte** [current/discovry#45]
It seems that google maps token has expired. Therefore, it's not possible to navigate through the places using the map.

**Comment by jonduarte** [comment]
ping @dlibanori @rmasoni

**Comment by rmasoni** [comment]
No idea where to go to fix this.

**Comment by dlibanori** [comment]
A API não expirou. Talvez o problema seja que o _Referer_ não está correto.

![screen shot 2015-03-03 at 11 23 13 am](https://cloud.githubusercontent.com/assets/27499/6464256/cadf66c8-c197-11e4-9bf5-1a20500d3d65.png)

**Comment by rmasoni** [comment]
いろんな言語に喋ろうか。

**Comment by jonduarte** [comment]
referer: discovry.herokuapp.com

**Comment by dlibanori** [comment]
![screen shot 2015-03-04 at 5 28 10 pm](https://cloud.githubusercontent.com/assets/27499/6492637/d94f98d4-c293-11e4-84d2-ba16d36a8287.png)

**Comment by jonduarte** [comment]
:clap: :clap:
